class DayTwo {
    public static void main(String[] args) {
        String s = "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n";

        String[] x = s.split("\n");
        int counter = 0;

        for (int i = 0; i < x.length; i++) {

            if (x[i].charAt(2) == 'X') { //lose
                counter += 0;
                if (x[i].charAt(0) == 'A') counter+= 3; //rock
                if (x[i].charAt(0) == 'B') counter+= 1; //paper
                if (x[i].charAt(0) == 'C') counter+= 2; //scissors
            }
            if (x[i].charAt(2) == 'Y') { //draw
                counter += 3;
                if (x[i].charAt(0) == 'A') counter+= 1;
                if (x[i].charAt(0) == 'B') counter+= 2;
                if (x[i].charAt(0) == 'C') counter+= 3;
            }
            if (x[i].charAt(2) == 'Z') { //win
                counter += 6;
                if (x[i].charAt(0) == 'A') counter+= 2;
                if (x[i].charAt(0) == 'B') counter+= 3;
                if (x[i].charAt(0) == 'C') counter+= 1;
            }
        }

        System.out.println(counter);
    }
}

//        for (int i = 0; i < x.length; i++) {
//            if (x[i].charAt(2) == 'X') counter += 1;
//            else if (x[i].charAt(2) == 'Y') counter += 2;
//            else if (x[i].charAt(2) == 'Z') counter += 3;
//            else {counter -= 99999999;}
//            counter += resultWinner(x[i]);
//            System.out.println(counter);
//        }
//    }
//
//    public static int resultWinner(String s) {
//        if (s.charAt(0) == 'A') { // rock
//            if (s.charAt(2) == 'Y') return 6; //paper
//            else if (s.charAt(2) == 'X') return 3; //rock
//            else if (s.charAt(2) == 'Z') return 0; //scissor
//        }
//        if (s.charAt(0) == 'B') { // paper
//            if (s.charAt(2) == 'Y') return 3; //paper
//            else if (s.charAt(2) == 'X') return 0; //rock
//            else if (s.charAt(2) == 'Z') return 6; //scissor
//        }
//        if (s.charAt(0) == 'C') { //scissor
//            if (s.charAt(2) == 'Y') return 0; //paper
//            else if (s.charAt(2) == 'X') return 6; //rock
//            else if (s.charAt(2) == 'Z') return 3; //scissor
//        }
//        return -9999999;
//    }